name: Run Python scripts on commit

on:
  push:
    branches:
      - master

jobs:
  run-scripts:
    name: Run Python scripts
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Rebuild site
        run: cd build_scripts && python render.py

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Script - Rebuilt site
